language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv run pip install pip==18.0'
  - 'pipenv sync'
script: 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'